var str1="Hello World";
console.log(str1);
var str2="I am \"double\" quoted string";
console.log(str2);
var str3='<a href="https://www.google.com" target="_blank">LINK</a>';
var str4="This is \t tab \t space";
console.log(str4);
var str5="I come first. "+"I am second. ";
console.log(str5);
str5+="I come third. ";
console.log(str5);
var name="Hari";
var str6="Hello Mr."+name+". Welcome!";
console.log(str6);
var str7="Hello ";
var str8="World";
str7+=str8;
var len=str1.length;
console.log("Length of str1 is "+len);
var c1=str1[0];
console.log("The first character in str1 is "+c1);
//Shows that strings are immutable but can be reassigned
str1="Welcome";
console.log("The new value of str1 is "+str1);
var c2=str1[2];
console.log("The third character of str1 is "+c2);
var c3=str1[str1.length-1];
console.log("The last character of str1 is "+c3);
var c4=str1[str1.length-4];
console.log("The fourth character from last in str1 is "+c4);
var str9="The"+" "+"End";
console.log(str9);